### ISSUE TITLE
Love it!

### ISSUE THREAD

**Issue by sei-jmattson** [openfun/learninglocker-docker#21]
After wrestling with Learning Locker for a while, I came across this repo.  Very clean and straightforward -- that makes it FUN, I guess.

Two questions: is there no way to reduce the size of the Learning Locker image?  I tried a multistage build with that one, and the production image was always missing some dependency or another.  Seems like it needs all the dev resources to run, whether in production or not!

Also, do you know if there is an adverse effect to mounting a volume into storage (and then it having no folders?)  Might be nice to add a `tar cf storage.tar storage` to the Dockerfile.  Then folks could just untar it on startup if needed, either with a custom entrypoint or and init container or whatever.

Great work!

**Comment by jmaupetit** [comment]
Thank you for your feedback :heart: 

> Two questions: is there no way to reduce the size of the Learning Locker image? I tried a multistage build with that one, and the production image was always missing some dependency or another. Seems like it needs all the dev resources to run, whether in production or not!

Things improved recently, but as LL is doing server side rendering, all the building stack is required to run in production, see https://github.com/LearningLocker/learninglocker/issues/1302

@lunika tried to improve the image size, but I think our biggest issue is the... dependencies size.

> Also, do you know if there is an adverse effect to mounting a volume into storage (and then it having no folders?) Might be nice to add a `tar cf storage.tar storage` to the Dockerfile. Then folks could just untar it on startup if needed, either with a custom entrypoint or and init container or whatever.

I am not sure to understand what you mean by "storage" or this archive you are mentioning. Can you be more explicit about what will be stored and what would be the purpose of such thing?

**Comment by sei-jmattson** [comment]
The LL build produces /app/storage with a subfolder structure and a file or two, presumably for the ui-server to store any artifacts.  

When one mounts a volume onto /app/storage, it masks the original contents.  

I thought keeping a tar of the original "storage" folder structure on the image would make it easy to recreate after mounting a persistent volume over it.  That is, of course, if it is even important.  (I don't know if the ui server will automatically recreate that folder structure when needed.)

**Comment by jmaupetit** [comment]
Thank you for this clarification. I'll let @lunika answer to this point as it's his work in action here :wink:

**Comment by lunika** [comment]
Hi @sei-jmattson thank you very much for your feedback :heart: 

>  Two questions: is there no way to reduce the size of the Learning Locker image? I tried a multistage build with that one, and the production image was always missing some dependency or another. Seems like it needs all the dev resources to run, whether in production or not!

I also tried a multi-stage build with the same result, dependencies where missing. The problem is they mixed dev and prod dependencies. Since version 2.8.2 it should be possible to create an artefact with only production dependencies (see: https://github.com/LearningLocker/learninglocker/issues/1302). 

But, the prod dependencies are still huge so the size will be significant.

> Also, do you know if there is an adverse effect to mounting a volume into storage (and then it having no folders?) Might be nice to add a `tar cf storage.tar storage` to the Dockerfile. Then folks could just untar it on startup if needed, either with a custom entrypoint or and init container or whatever.

For this point I think you have multiple solutions:

- You can set the `FS_LOCAL_ENDPOINT` environment variable with the location you want on your server, it can be outside the `/app` directory. While you have write and read permissions it will works. And of course you can mount a persistent volume in this location.
- If you test the previous point you will notice that LL will create the subdirectories *when* it will needs them. So you can mount an empty dir in `/app/storage` and share this volume with all the LL instances you want.

I will improve the docker-compose config with a shared volume and using the `FS_LOCAL_ENDPOINT` to have a complete example.

**Comment by sei-jmattson** [comment]
Great, thanks.  I appreciate the info!
