### ISSUE TITLE
Learning locker and xapi-service image versions are outdated

### ISSUE THREAD

**Issue by chhch** [openfun/learninglocker-docker#64]
The current learning locker version is [v7.0.0](https://github.com/LearningLocker/learninglocker/tags) and the current xapi-service version is [v3.7.1](https://github.com/LearningLocker/xapi-service/tags).

**Comment by sampaccoud** [comment]
@chhch We stopped using learninglocker at France Université Numérique because it was not easy to scale it to our needs and the support proposed by its creators was beyond our means. We have moved to our own solution based on Elasticsearch+Kibana. You can find more info here: https://github.com/openfun/ralph.

This repository is now deprecated and we have added a mention in its description :pray:

**Comment by chhch** [comment]
Thanks for the response. _Ralph_ sounds interesting, but I will stick with [this fork](https://github.com/albertinisg/learninglocker-docker) for now.
